services:

  opensearch-art:
    build: ./opensearch
    container_name: opensearch-art
    environment:
      discovery.type: single-node
      node.name: opensearch
      network.host: 0.0.0.0
      DISABLE_SECURITY_PLUGIN: true
      logger.level: info
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: Mysupersecretpassword_123
      OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  opensearch-dashboards-art:
    build: ./opensearch-dashboards
    container_name: opensearch-art_dashboards
    ports:
      - "5601:5601"
    expose:
      - 5601
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-art:9200"]'
      DISABLE_SECURITY_PLUGIN: true
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
    depends_on:
      opensearch-art:
        condition: service_healthy
    networks:
      - opensearch-net

networks:
  opensearch-net:
